// SCANIQ — knowledge base data: categories, archive sources, value-matrix metadata.
// This file rarely changes; app.js (loaded after this) depends on these globals.


let imgB64=null,imgMime='image/jpeg',selCat='auto';
let hist=JSON.parse(localStorage.getItem('sq4_hist')||'[]');
let scanCount=parseInt(localStorage.getItem('sq4_cnt')||'0');
document.getElementById('scan-counter').textContent=scanCount;
const API_PROXY='https://scaniq-proxy.montecarlo-news24.workers.dev';
const ARCHIVE_DB = {
  animals: {
    sources:[
      {icon:'🔴',name:'IUCN Red List',url:'iucnredlist.org',info:'Conservation status: LC/NT/VU/EN/CR/EW/EX classification, population trend, habitat'},
      {icon:'🌿',name:'CITES Appendices',url:'cites.org',info:'Trade regulations: Appendix I (banned), II (controlled), III (monitored)'},
      {icon:'🐾',name:'Smithsonian National Zoo',url:'nationalzoo.si.edu',info:'Species biology, behavior, diet, lifespan, captive care data'},
      {icon:'📊',name:'GBIF — Global Biodiversity',url:'gbif.org',info:'Occurrence records, geographic range, subspecies taxonomy'},
      {icon:'💰',name:'Exotic Pet Market Data',url:'fauna-classifieds.com',info:'Legal trade prices, breeder estimates, import costs'},
          {icon:'📖',name:'Wikipedia — Species Articles',url:'en.wikipedia.org',info:'Taxonomy, behavior, habitat, conservation history, cultural significance, subspecies list, phylogenetic tree'},
      {icon:'📖',name:'Wikipedia — Species Articles',url:'en.wikipedia.org',info:'Taxonomy, behavior, habitat, conservation history, cultural significance, subspecies, phylogenetic classification'},
    ],
    dims:['monetary','rarity','ecological','scientific','heritage','legal'],
    live:false,
  },
  plants: {
    sources:[
      {icon:'🔴',name:'IUCN Red List — Plants',url:'iucnredlist.org',info:'Endangered status, endemic range, extinction risk score'},
      {icon:'🌿',name:'CITES Flora Appendices',url:'cites.org',info:'Trade protection level for orchids, cacti, cycads, tree species'},
      {icon:'🌱',name:'Kew Royal Botanic Gardens',url:'kew.org/science',info:'Taxonomic classification, seed bank records, conservation priority'},
      {icon:'💊',name:'WHO Monographs on Medicinal Plants',url:'who.int',info:'Traditional & clinical medicinal uses, active compounds, dosage'},
      {icon:'🌳',name:'Monumental Trees Database',url:'monumentaltrees.com',info:'Champion tree records, age estimates, girth measurements'},
      {icon:'💰',name:'RHS Plant Finder & Rare Plant Auctions',url:'rhs.org.uk',info:'Market prices for rare species, nursery availability, collector demand'},
          {icon:'📖',name:'Wikipedia — Botany & Flora',url:'en.wikipedia.org',info:'Taxonomic classification, native range, ecological role, ethnobotanical uses, cultivation history, poisonous/edible notes'},
      {icon:'📖',name:'Wikipedia — Botany & Flora',url:'en.wikipedia.org',info:'Taxonomic classification, native range, ecological role, ethnobotanical uses, cultivation history, poisonous or edible notes'},
    ],
    dims:['monetary','rarity','medicinal','ecological','scientific','heritage'],
    live:false,
  },
  currency: {
    sources:[
      {icon:'🪙',name:'NGC Coin Census',url:'ngccoin.com',info:'Professional grading (MS/PR 1-70), population reports, finest known'},
      {icon:'🏛️',name:'PCGS CoinFacts',url:'pcgs.com/coinfacts',info:'Mintage figures, die varieties, historical auction prices'},
      {icon:'📖',name:'Numista World Coin Database',url:'numista.com',info:'Catalog numbers, specifications, issuing authority, metal composition'},
      {icon:'🔨',name:'Heritage Auctions Archives',url:'ha.com/coins',info:'Realized auction prices, lot descriptions, provenance history'},
      {icon:'📜',name:'Standard Catalog of World Coins',url:'krause.com',info:'Krause-Mishler numbers, rarity ratings, price guide by grade'},
      {icon:'💵',name:'CoinMarketCap (Crypto)',url:'coinmarketcap.com',info:'Real-time crypto prices, market cap, volume — for digital currencies'},
      {icon:'📈',name:'XE Currency + OANDA',url:'xe.com',info:'Live fiat exchange rates for modern banknotes'},
          {icon:'📖',name:'Wikipedia — Numismatics',url:'en.wikipedia.org',info:'Coin/banknote history, issuing authority, monetary policy context, historical exchange rates, design iconography'},
      {icon:'📖',name:'Wikipedia — Numismatics & Money',url:'en.wikipedia.org',info:'Coin or banknote history, issuing authority, monetary policy context, historical exchange rates, design iconography'},
    ],
    dims:['monetary','numismatic','historical','rarity','condition','heritage'],
    live:true,
  },
  palaces: {
    sources:[
      {icon:'🏛️',name:'UNESCO World Heritage List',url:'whc.unesco.org',info:'WH status, Outstanding Universal Value criteria, buffer zone regulations'},
      {icon:'🏰',name:'Historic England / ICOMOS',url:'historicengland.org.uk',info:'Listed building grade (I/II*/II), scheduled monument status'},
      {icon:'📐',name:'Aga Khan Trust for Culture',url:'akdn.org/architecture',info:'Islamic palace & fortress documentation, restoration records'},
      {icon:'💰',name:'Savills World Heritage Property Index',url:'savills.com',info:'Historic estate valuations, comparable transactions, heritage premium'},
      {icon:'🗺️',name:'Europeana Heritage Collections',url:'europeana.eu',info:'Digitized architectural drawings, historical photographs, archival plans'},
      {icon:'📜',name:'National Trust / Châteaux de France',url:'nationaltrust.org.uk',info:'Ownership history, restoration costs, visitor revenue data'},
          {icon:'📖',name:'Wikipedia — Historic Palaces',url:'en.wikipedia.org',info:'Construction date, ruling dynasty, architectural style, major renovations, current use, visitor figures, notable events'},
      {icon:'📖',name:'Wikipedia — Historic Palaces',url:'en.wikipedia.org',info:'Construction date, ruling dynasty, architectural style, major renovations, current use, visitor figures, notable events'},
    ],
    dims:['monetary','heritage','architectural','rarity','legal','tourism'],
    live:false,
  },
  artifacts: {
    sources:[
      {icon:'🏺',name:'British Museum Collection Online',url:'britishmuseum.org/collection',info:'Object database: culture, period, provenance, excavation site, material'},
      {icon:'🌐',name:'Europeana — Cultural Heritage',url:'europeana.eu',info:'5M+ digitized artifacts from 3,000+ European institutions'},
      {icon:'🔍',name:'Art Loss Register',url:'artloss.com',info:'Stolen/looted artifact database, provenance verification'},
      {icon:'📜',name:'UNESCO 1970 Convention Database',url:'unesco.org',info:'Illicit trafficking laws, country of origin claims, repatriation cases'},
      {icon:'🔨',name:'Sothebys / Christies Antiquities',url:'sothebys.com',info:'Auction estimates, realized prices, provenance documentation standards'},
      {icon:'🏛️',name:'Metropolitan Museum — Heilbrunn Timeline',url:'metmuseum.org',info:'Art historical context, civilization chronology, iconographic analysis'},
      {icon:'🌍',name:'ASOR Cultural Heritage Initiatives',url:'asor-syrianheritage.org',info:'Conflict-zone artifact tracking, site damage assessment'},
          {icon:'📖',name:'Wikipedia — Archaeology',url:'en.wikipedia.org',info:'Discovery context, excavation history, cultural period, iconographic meaning, museum holdings, repatriation disputes'},
      {icon:'📖',name:'Wikipedia — Archaeology & Artifacts',url:'en.wikipedia.org',info:'Discovery context, excavation history, cultural period, iconographic meaning, museum holdings, repatriation disputes'},
    ],
    dims:['monetary','heritage','historical','rarity','scientific','legal'],
    live:false,
  },
  metals: {
    sources:[
      {icon:'📈',name:'LBMA — London Bullion Market',url:'lbma.org.uk',info:'Official gold/silver/platinum/palladium spot prices, AM/PM fix'},
      {icon:'⚡',name:'LME — London Metal Exchange',url:'lme.com',info:'Base metals: copper, aluminum, zinc, lead, nickel, tin — live prices'},
      {icon:'📊',name:'Kitco Metals',url:'kitco.com',info:'Live spot prices, historical charts, scrap dealer pricing'},
      {icon:'🏦',name:'World Gold Council',url:'gold.org',info:'Investment demand, central bank reserves, jewelry consumption data'},
      {icon:'🧪',name:'CRC Handbook of Chemistry',url:'crcpress.com',info:'Physical properties, atomic weight, melting point, conductivity data'},
      {icon:'🌍',name:'USGS Minerals Information',url:'usgs.gov/minerals',info:'Global reserves, mine production, country-by-country output data'},
          {icon:'📖',name:'Wikipedia — Metals & Metallurgy',url:'en.wikipedia.org',info:'Atomic properties, discovery history, industrial applications, major deposits, refining processes, alloy information'},
      {icon:'📖',name:'Wikipedia — Metals & Metallurgy',url:'en.wikipedia.org',info:'Atomic properties, discovery history, industrial applications, major deposits, refining processes, alloy information'},
    ],
    dims:['monetary','industrial','investment','rarity','purity','historical'],
    live:true,
  },
  energy: {
    sources:[
      {icon:'🛢️',name:'EIA — US Energy Information',url:'eia.gov',info:'WTI/Brent crude prices, natural gas, coal, refinery data'},
      {icon:'🌍',name:'OPEC Monthly Oil Market Report',url:'opec.org',info:'Production quotas, member output, demand forecasts'},
      {icon:'📊',name:'IEA — International Energy Agency',url:'iea.org',info:'Global energy mix, renewable capacity, fossil fuel transition data'},
      {icon:'⚡',name:'S&P Global Platts',url:'spglobal.com/commodities',info:'Real-time energy commodity prices, LNG spot market'},
      {icon:'📈',name:'CME Group Energy Futures',url:'cmegroup.com',info:'Oil & gas futures contracts, options data, delivery specifications'},
          {icon:'📖',name:'Wikipedia — Energy Resources',url:'en.wikipedia.org',info:'Formation geology, reserve estimates, extraction methods, environmental impact, geopolitical significance, peak production data'},
      {icon:'📖',name:'Wikipedia — Energy Resources',url:'en.wikipedia.org',info:'Formation geology, reserve estimates, extraction methods, environmental impact, geopolitical significance, peak production data'},
    ],
    dims:['monetary','industrial','investment','rarity','ecological','historical'],
    live:true,
  },
  space: {
    sources:[
      {icon:'🚀',name:'NASA/IPAC Extragalactic Database',url:'ned.ipac.caltech.edu',info:'Galaxy distances, redshift, morphology, photometric data'},
      {icon:'🌌',name:'ESA Hubble & Webb Archives',url:'esahubble.org',info:'Deep field imagery, spectroscopic data, nebula catalogs'},
      {icon:'⭐',name:'SIMBAD Astronomical Database',url:'simbad.u-strasbg.fr',info:'Star classifications, coordinates, proper motion, magnitude'},
      {icon:'☄️',name:'JPL Small-Body Database',url:'ssd.jpl.nasa.gov',info:'Asteroid/comet orbital elements, composition, close approach data'},
      {icon:'🌙',name:'Lunar and Planetary Institute',url:'lpi.usra.edu',info:'Planetary geology, mission data, crater catalogs'},
      {icon:'📡',name:'arXiv Astrophysics',url:'arxiv.org/astro-ph',info:'Latest peer-reviewed research on all astronomical objects'},
          {icon:'📖',name:'Wikipedia — Astronomy',url:'en.wikipedia.org',info:'Discovery date, constellation location, physical parameters, observation history, mythology, notable missions, stellar classification'},
      {icon:'📖',name:'Wikipedia — Astronomy & Cosmos',url:'en.wikipedia.org',info:'Discovery date, constellation, physical parameters, observation history, mythology, notable missions, stellar classification'},
    ],
    dims:['scientific','rarity','historical','aesthetic','monetary','ecological'],
    live:false,
  },
  art: {
    sources:[
      {icon:'🎨',name:'Artnet Price Database',url:'artnet.com/price-database',info:'650,000+ auction results, artist analytics, market trend indices'},
      {icon:'🏛️',name:'Artsy — Art Market Data',url:'artsy.net',info:'Artist career stages, gallery representation, price ranges'},
      {icon:'🔍',name:'Art Loss Register',url:'artloss.com',info:'Stolen art database, provenance research, authentication records'},
      {icon:'📜',name:'TEFAF Art Market Report',url:'tefaf.com',info:'Annual global art market size, segment analysis, collector trends'},
      {icon:'🔨',name:'Sothebys / Christies / Phillips',url:'sothebys.com',info:'Pre-sale estimates, hammer prices, buyer premium calculations'},
      {icon:'🖼️',name:'Grove Art Online / Oxford Art',url:'grovemuseum.com',info:'Artist biographies, movement classifications, iconographic analysis'},
          {icon:'📖',name:'Wikipedia — Art History',url:'en.wikipedia.org',info:'Artist biography, movement classification, commission history, stylistic analysis, exhibition record, critical reception'},
      {icon:'📖',name:'Wikipedia — Art History',url:'en.wikipedia.org',info:'Artist biography, movement classification, commission history, stylistic analysis, exhibition record, critical reception'},
    ],
    dims:['monetary','aesthetic','provenance','rarity','heritage','condition'],
    live:false,
  },
  gems: {
    sources:[
      {icon:'💎',name:'GIA — Gemological Institute',url:'gia.edu',info:'4Cs grading (cut/color/clarity/carat), certification database, rarity scale'},
      {icon:'🔬',name:'Gübelin Gem Lab',url:'gubelingemlab.com',info:'Geographic origin determination, treatment detection, inclusion mapping'},
      {icon:'📊',name:'Rapaport Diamond Report',url:'rapaport.com',info:'Weekly diamond price list by cut/color/clarity/carat — industry standard'},
      {icon:'🌍',name:'ICA — Intl. Colored Gemstone Assoc.',url:'gemstone.org',info:'Colored stone market, origin premiums, treatment disclosure standards'},
      {icon:'🏔️',name:'Mindat.org Mineralogy Database',url:'mindat.org',info:'Mineral species, crystal system, locality data, type specimens'},
      {icon:'🔨',name:'Christie\'s Magnificent Jewels',url:'christies.com/jewels',info:'Record auction prices for colored stones, signed jewelry premiums'},
          {icon:'📖',name:'Wikipedia — Gemology & Minerals',url:'en.wikipedia.org',info:'Crystal structure, Mohs hardness, refractive index, famous specimens, mining locations, historical lore, treatment history'},
      {icon:'📖',name:'Wikipedia — Gemology & Minerals',url:'en.wikipedia.org',info:'Crystal structure, Mohs hardness, refractive index, famous specimens, mining locations, historical lore, treatment methods'},
    ],
    dims:['monetary','rarity','aesthetic','scientific','condition','heritage'],
    live:false,
  },
  fashion: {
    sources:[
      {icon:'👗',name:'Vogue Business Market Reports',url:'voguebusiness.com',info:'Brand valuations, trend forecasting, luxury segment price analysis'},
      {icon:'💼',name:'Vestiaire Collective / The RealReal',url:'vestiairecollective.com',info:'Pre-owned luxury resale prices, authentication data, demand scores'},
      {icon:'📊',name:'Bain & Company Luxury Study',url:'bain.com/luxury',info:'Annual personal luxury goods market size, brand growth rates'},
      {icon:'🧵',name:'Business of Fashion',url:'businessoffashion.com',info:'Designer profiles, brand strategy, production cost transparency'},
      {icon:'🏷️',name:'Statista Apparel Market',url:'statista.com',info:'Category market size, average selling prices, consumer demographics'},
          {icon:'📖',name:'Wikipedia — Fashion History',url:'en.wikipedia.org',info:'Brand founding history, designer biographies, iconic collections, cultural impact, manufacturing regions, fashion week presence'},
      {icon:'📖',name:'Wikipedia — Fashion History',url:'en.wikipedia.org',info:'Brand founding, designer biographies, iconic collections, cultural impact, manufacturing regions, fashion week presence'},
    ],
    dims:['monetary','aesthetic','rarity','heritage','condition','provenance'],
    live:false,
  },
  realestate: {
    sources:[
      {icon:'🏠',name:'Knight Frank Prime Index',url:'knightfrank.com',info:'Prime residential prices by city, luxury market performance'},
      {icon:'🌍',name:'Global Property Guide',url:'globalpropertyguide.com',info:'Price per sqm by country/city, rental yields, legal framework'},
      {icon:'📊',name:'MSCI Real Estate Analytics',url:'msci.com/real-estate',info:'Institutional property values, cap rates, total return indices'},
      {icon:'🗺️',name:'Numbeo Cost of Living',url:'numbeo.com',info:'City-level price comparisons, affordability ratios, expat data'},
      {icon:'🏛️',name:'Savills World Research',url:'savills.com/research',info:'Cross-border investment flows, emerging market opportunities'},
          {icon:'📖',name:'Wikipedia — Real Estate & Urbanism',url:'en.wikipedia.org',info:'City/region history, zoning laws background, urban development context, landmark designations, neighborhood character'},
      {icon:'📖',name:'Wikipedia — Real Estate & Urbanism',url:'en.wikipedia.org',info:'City history, zoning background, urban development context, landmark designations, neighborhood character, demographics'},
    ],
    dims:['monetary','rarity','heritage','legal','tourism','ecological'],
    live:false,
  },
  medicine: {
    sources:[
      {icon:'💊',name:'WHO Essential Medicines List',url:'who.int/medicines',info:'Essential drug classifications, therapeutic categories, generic availability'},
      {icon:'🔬',name:'PubMed / MEDLINE',url:'pubmed.ncbi.nlm.nih.gov',info:'35M+ biomedical citations, clinical trial results, drug efficacy data'},
      {icon:'📋',name:'FDA Drug Database',url:'fda.gov/drugs',info:'Approval status, NDC codes, manufacturer, dosage forms, warnings'},
      {icon:'💰',name:'GoodRx Drug Pricing',url:'goodrx.com',info:'US retail prices, insurance coverage, discount program data'},
      {icon:'🌡️',name:'Drugs.com Interactions',url:'drugs.com',info:'Interaction checker, side effects database, professional monographs'},
          {icon:'📖',name:'Wikipedia — Pharmacology & Medicine',url:'en.wikipedia.org',info:'Drug mechanism of action, discovery timeline, clinical trials history, side effect profile, patent expiry, generic availability'},
      {icon:'📖',name:'Wikipedia — Pharmacology & Medicine',url:'en.wikipedia.org',info:'Drug mechanism, discovery timeline, clinical trial history, side effect profile, patent expiry, generic availability'},
    ],
    dims:['scientific','monetary','rarity','legal','heritage','condition'],
    live:false,
  },
  books: {
    sources:[
      {icon:'📚',name:'Rare Books — ABAA',url:'abaa.org',info:'Antiquarian booksellers pricing, first edition identification, bibliographic records'},
      {icon:'🔨',name:'Christie\'s & Sothebys Books',url:'christies.com/books',info:'Manuscript & rare book auction records, illuminated manuscript data'},
      {icon:'📖',name:'WorldCat — OCLC',url:'worldcat.org',info:'Holdings of 10,000+ libraries, edition records, physical descriptions'},
      {icon:'🏛️',name:'British Library Digitized Manuscripts',url:'bl.uk/manuscripts',info:'Medieval manuscripts, provenance chains, digitized folios'},
      {icon:'📜',name:'ISTC — Incunabula Short Title Catalogue',url:'data.cerl.org/istc',info:'Books printed before 1501, holding libraries, census of survivors'},
          {icon:'📖',name:'Wikipedia — Bibliography & Rare Books',url:'en.wikipedia.org',info:'Author biography, publication date, literary significance, banned/censored history, translation count, adaptation records'},
      {icon:'📖',name:'Wikipedia — Bibliography & Literature',url:'en.wikipedia.org',info:'Author biography, publication date, literary significance, censorship history, translation count, adaptation records'},
    ],
    dims:['monetary','rarity','historical','condition','provenance','heritage'],
    live:false,
  },
  cars: {
    sources:[
      {icon:'🚗',name:'Hagerty Valuation Tools',url:'hagerty.com/valuation',info:'Classic car values by condition (#1-#4), trend data, concours premiums'},
      {icon:'🏎️',name:'RM Sothebys / Gooding & Co',url:'rmsothebys.com',info:'Collector car auction results, consignment estimates, market reports'},
      {icon:'📊',name:'NADA Guides / Kelley Blue Book',url:'nadaguides.com',info:'Current market values, trade-in vs retail spread, mileage adjustments'},
      {icon:'🔧',name:'VIN History — Carfax / AutoCheck',url:'carfax.com',info:'Accident history, service records, title status, ownership count'},
      {icon:'🏁',name:'Classic & Sports Car Price Guide',url:'classicandsportscar.com',info:'European classic market, model histories, investment grade analysis'},
          {icon:'📖',name:'Wikipedia — Automotive History',url:'en.wikipedia.org',info:'Model production years, engine specifications, designer/manufacturer history, motorsport record, recalls, cultural icon status'},
      {icon:'📖',name:'Wikipedia — Automotive History',url:'en.wikipedia.org',info:'Model production years, engine specs, designer history, motorsport record, notable recalls, cultural icon status'},
    ],
    dims:['monetary','rarity','heritage','condition','aesthetic','provenance'],
    live:false,
  },
  flags: {
    sources:[
      {icon:'🚩',name:'FOTW — Flags of the World',url:'flagspot.net',info:'Vexillological database: history, symbolism, usage rules, variants'},
      {icon:'🌍',name:'CIA World Factbook',url:'cia.gov/the-world-factbook',info:'Country profiles, government type, economy, population, geography'},
      {icon:'📊',name:'Statista Media & Advertising',url:'statista.com/advertising',info:'Ad spend by country, billboard CPM rates, digital vs OOH split'},
      {icon:'🏛️',name:'UN Member States Data',url:'un.org/en/about-us/member-states',info:'Membership date, treaty obligations, peacekeeping contributions'},
          {icon:'📖',name:'Wikipedia — Vexillology & Countries',url:'en.wikipedia.org',info:'Flag design history, symbolism of colors and emblems, historical variants, country founding, constitutional context'},
      {icon:'📖',name:'Wikipedia — Vexillology & Nations',url:'en.wikipedia.org',info:'Flag design history, color and emblem symbolism, historical variants, country founding date, constitutional context'},
    ],
    dims:['heritage','historical','rarity','scientific','monetary','aesthetic'],
    live:false,
  },
  marine: {
    sources:[
      {icon:'🐠',name:'FishBase Global Database',url:'fishbase.org',info:'50,000+ species, taxonomy, habitat, trophic level, max size'},
      {icon:'🌊',name:'OBIS — Ocean Biodiversity Info',url:'obis.org',info:'Marine species occurrence records, depth range, salinity tolerance'},
      {icon:'🔴',name:'IUCN Marine Species',url:'iucnredlist.org',info:'Conservation status for fish, corals, marine mammals, sea turtles'},
      {icon:'💰',name:'FAO Global Aquaculture Data',url:'fao.org/fishery',info:'Species trade volumes, export prices, aquaculture production values'},
      {icon:'🐚',name:'Coral Triangle Initiative',url:'coraltriangleinitiative.org',info:'Reef biodiversity hotspots, bleaching records, protected area data'},
          {icon:'📖',name:'Wikipedia — Marine Biology',url:'en.wikipedia.org',info:'Species taxonomy, habitat depth range, reproductive cycle, predator-prey relationships, bioluminescence, migration patterns'},
      {icon:'📖',name:'Wikipedia — Marine Biology',url:'en.wikipedia.org',info:'Species taxonomy, habitat depth range, reproductive cycle, predator-prey relations, bioluminescence, migration patterns'},
    ],
    dims:['monetary','rarity','ecological','scientific','heritage','legal'],
    live:false,
  },
  architecture: {
    sources:[
      {icon:'🏛️',name:'Archnet — MIT Islamic Architecture',url:'archnet.org',info:'50,000+ buildings, architects, sites, photographic archives'},
      {icon:'🏗️',name:'Dezeen / ArchDaily Projects',url:'dezeen.com',info:'Contemporary architecture database, cost per sqm estimates, awards'},
      {icon:'📐',name:'DOCOMOMO International',url:'docomomo.com',info:'Modern movement buildings at risk, documentation, preservation status'},
      {icon:'💰',name:'RICS Building Cost Information',url:'rics.org/bcis',info:'UK & global construction costs per m² by building type and region'},
      {icon:'🌍',name:'UNESCO World Architecture',url:'whc.unesco.org',info:'Architectural world heritage sites, integrity assessments'},
          {icon:'📖',name:'Wikipedia — Architecture History',url:'en.wikipedia.org',info:'Architectural style definition, period characteristics, key architects, structural innovations, regional variants, famous examples'},
      {icon:'📖',name:'Wikipedia — Architecture History',url:'en.wikipedia.org',info:'Style definitions, period characteristics, key architects, structural innovations, regional variants, famous examples'},
    ],
    dims:['monetary','heritage','aesthetic','rarity','architectural','legal'],
    live:false,
  },
  psychology: {
    sources:[
      {icon:'🧠',name:'APA PsycINFO',url:'apa.org/psycinfo',info:'5M+ psychology records, DSM classifications, research methodologies'},
      {icon:'📋',name:'DSM-5-TR / ICD-11',url:'psychiatry.org/dsm5',info:'Diagnostic criteria, prevalence rates, differential diagnosis'},
      {icon:'🔬',name:'PubMed Psychology',url:'pubmed.ncbi.nlm.nih.gov',info:'Peer-reviewed clinical studies, meta-analyses, treatment outcomes'},
      {icon:'📊',name:'WHO Mental Health Atlas',url:'who.int/mental_health',info:'Global prevalence data, healthcare system resources, treatment gaps'},
          {icon:'📖',name:'Wikipedia — Psychology & Psychiatry',url:'en.wikipedia.org',info:'Theoretical framework, founding psychologists, key experiments, criticisms, current clinical applications, cross-cultural validity'},
      {icon:'📖',name:'Wikipedia — Psychology & Psychiatry',url:'en.wikipedia.org',info:'Theoretical framework, founding figures, key experiments, criticisms, clinical applications, cross-cultural validity'},
    ],
    dims:['scientific','heritage','historical','rarity','aesthetic','legal'],
    live:false,
  },
  religion: {
    sources:[
      {icon:'☪️',name:'Encyclopedia of Religion (Macmillan)',url:'religion.oxfordre.com',info:'Theological doctrines, ritual practices, historical development'},
      {icon:'📜',name:'JSTOR Sacred Texts Collection',url:'jstor.org',info:'Primary religious texts, scholarly commentary, translation archives'},
      {icon:'🌍',name:'Pew Research — Global Religion',url:'pewresearch.org/religion',info:'Adherent demographics, practice rates, interfaith relations data'},
      {icon:'🏛️',name:'Quranic Arabic Corpus',url:'corpus.quran.com',info:'Morphological analysis, word-by-word breakdown, classical tafsir'},
      {icon:'🗺️',name:'World Religion Database',url:'worldreligiondatabase.org',info:'580+ denominations, historical membership data, geographic spread'},
          {icon:'📖',name:'Wikipedia — Religion & Theology',url:'en.wikipedia.org',info:'Founding history, core beliefs, sacred texts, major denominations, geographic spread, historical schisms, interfaith relations'},
      {icon:'📖',name:'Wikipedia — Religion & Theology',url:'en.wikipedia.org',info:'Founding history, core beliefs, sacred texts, denominations, geographic spread, historical schisms, interfaith context'},
    ],
    dims:['heritage','historical','rarity','scientific','aesthetic','legal'],
    live:false,
  },
  sociology: {
    sources:[
      {icon:'👥',name:'World Bank Open Data',url:'data.worldbank.org',info:'GDP, inequality (Gini), poverty rates, social indicators by country'},
      {icon:'📊',name:'OECD Better Life Index',url:'oecdbetterlifeindex.org',info:'Quality of life metrics: education, safety, community, environment'},
      {icon:'🌍',name:'UN Human Development Reports',url:'hdr.undp.org',info:'HDI rankings, gender inequality, multidimensional poverty index'},
      {icon:'🔬',name:'JSTOR Sociology Journals',url:'jstor.org/sociology',info:'Peer-reviewed sociological research, demographic studies, field work'},
          {icon:'📖',name:'Wikipedia — Sociology & Anthropology',url:'en.wikipedia.org',info:'Theoretical origins, key sociologists, related movements, empirical studies, cross-cultural comparisons, contemporary relevance'},
      {icon:'📖',name:'Wikipedia — Sociology & Anthropology',url:'en.wikipedia.org',info:'Theoretical origins, key sociologists, related movements, empirical studies, cross-cultural comparisons, contemporary relevance'},
    ],
    dims:['scientific','heritage','historical','rarity','ecological','aesthetic'],
    live:false,
  },
  construction: {
    sources:[
      {icon:'🏗️',name:'RSMeans Construction Data',url:'rsmeans.com',info:'Unit cost data by material, region, crew size — US & international'},
      {icon:'💰',name:'BCIS — Building Cost Index',url:'rics.org/bcis',info:'UK tender price index, regional factors, material cost trends'},
      {icon:'🌍',name:'Turner & Townsend Cost Survey',url:'turnerandtownsend.com',info:'International construction cost benchmarks: 90 cities worldwide'},
      {icon:'🏠',name:'ICE — Embodied Carbon Database',url:'ice.unige.ch',info:'Carbon coefficients per kg of material, lifecycle assessment data'},
      {icon:'🔧',name:'Means Heavy Construction',url:'rsmeans.com/heavy',info:'Civil engineering costs: earthwork, utilities, site work, bridges'},
          {icon:'📖',name:'Wikipedia — Construction Materials',url:'en.wikipedia.org',info:'Material composition, historical use, structural properties, environmental concerns, manufacturing process, building code standards'},
      {icon:'📖',name:'Wikipedia — Construction & Materials',url:'en.wikipedia.org',info:'Material composition, historical use, structural properties, environmental concerns, manufacturing process, building codes'},
    ],
    dims:['monetary','industrial','ecological','scientific','rarity','heritage'],
    live:false,
  },
  food: {
    sources:[
      {icon:'🍕',name:'FAO Food Price Index',url:'fao.org/worldfoodsituation',info:'Monthly commodity food prices: cereals, dairy, meat, oils, sugar'},
      {icon:'⭐',name:'Michelin Guide Archives',url:'guide.michelin.com',info:'Restaurant stars, Bib Gourmand, price categories, inspectors notes'},
      {icon:'🔬',name:'USDA FoodData Central',url:'fdc.nal.usda.gov',info:'Nutritional composition, serving sizes, origin, processing method'},
      {icon:'🌍',name:'Taste Atlas — Traditional Food',url:'tasteatlas.com',info:'Regional dishes, ingredient origins, cultural context, authenticity data'},
      {icon:'💰',name:'Statista Food Service Market',url:'statista.com/food',info:'Average meal prices by country, restaurant segment data, delivery trends'},
          {icon:'📖',name:'Wikipedia — Culinary Arts',url:'en.wikipedia.org',info:'Dish origin, historical recipe evolution, regional variations, cultural significance, dietary classification, Michelin recognition'},
      {icon:'📖',name:'Wikipedia — Culinary Arts & Food',url:'en.wikipedia.org',info:'Dish origin story, recipe evolution, regional variations, cultural significance, dietary classification, Michelin recognition'},
    ],
    dims:['monetary','heritage','rarity','scientific','aesthetic','ecological'],
    live:false,
  },
  ads: {
    sources:[
      {icon:'📢',name:'WARC Global Ad Spend',url:'warc.com',info:'Advertising expenditure by country, medium, category — annual data'},
      {icon:'📊',name:'Statista Advertising Market',url:'statista.com/advertising',info:'CPM/CPC rates by platform, OOH billboard inventory pricing'},
      {icon:'📱',name:'Meta / Google Ad Benchmarks',url:'business.facebook.com',info:'Average CPC, CTR, CPM by industry vertical and region'},
      {icon:'🏙️',name:'OAAA — Out of Home Association',url:'oaaa.org',info:'Billboard/transit/digital OOH rates, audience measurement, formats'},
      {icon:'🎯',name:'eMarketer Ad Spending',url:'emarketer.com',info:'Digital ad spend forecasts, platform market shares, brand safety data'},
          {icon:'📖',name:'Wikipedia — Advertising History',url:'en.wikipedia.org',info:'Medium history, landmark campaigns, regulatory frameworks, psychological theories applied, cultural impact, censorship cases'},
      {icon:'📖',name:'Wikipedia — Advertising History',url:'en.wikipedia.org',info:'Medium history, landmark campaigns, regulatory frameworks, psychological theories applied, cultural impact, censorship cases'},
    ],
    dims:['monetary','aesthetic','rarity','scientific','heritage','industrial'],
    live:false,
  },
  gaming: {
    sources:[
      {icon:'🎮',name:'IGDB — Internet Game Database',url:'igdb.com',info:'Game metadata, release dates, genres, platforms, aggregated scores'},
      {icon:'💰',name:'VGPC — Video Game Price Charting',url:'pricecharting.com',info:'Sealed/CIB/loose prices for 30,000+ games, graded WATA values'},
      {icon:'🏆',name:'Metacritic / OpenCritic',url:'metacritic.com',info:'Review aggregation, critic scores, user scores, release context'},
      {icon:'📦',name:'WATA Games Certification',url:'watagames.com',info:'Sealed game grading, print run population, auction records'},
      {icon:'📊',name:'Newzoo Games Market Report',url:'newzoo.com',info:'Global games market size, platform splits, mobile vs PC/console'},
          {icon:'📖',name:'Wikipedia — Video Games',url:'en.wikipedia.org',info:'Game release history, developer/publisher background, genre classification, critical reception, sales figures, sequel lineage'},
      {icon:'📖',name:'Wikipedia — Video Game History',url:'en.wikipedia.org',info:'Game release history, developer background, genre classification, critical reception, global sales figures, sequel lineage'},
    ],
    dims:['monetary','rarity','heritage','condition','aesthetic','provenance'],
    live:false,
  },
  weapons: {
    sources:[
      {icon:'🪖',name:'Jane\'s Defence Equipment',url:'janes.com',info:'Military hardware specifications, country operators, production numbers'},
      {icon:'🏛️',name:'Royal Armouries Collection',url:'royalarmouries.org',info:'Historical weapons database, metallurgical analysis, period attribution'},
      {icon:'🔫',name:'NRA National Firearms Museum',url:'nrafoundation.org',info:'Antique firearm identification, maker marks, production dates'},
      {icon:'📜',name:'SIPRI Arms Transfers Database',url:'sipri.org/databases/armstransfers',info:'International arms trade data, export licenses, conflict use records'},
      {icon:'💰',name:'Rock Island Auction — Firearms',url:'rockislandauction.com',info:'Antique & collectible weapons auction results, rarity assessments'},
          {icon:'📖',name:'Wikipedia — Military History',url:'en.wikipedia.org',info:'Weapon design history, conflicts used in, technical specifications, notable variants, manufacturing country, decommission date'},
      {icon:'📖',name:'Wikipedia — Military History',url:'en.wikipedia.org',info:'Weapon design origin, conflicts used in, technical specifications, notable variants, manufacturing country, decommission date'},
    ],
    dims:['monetary','heritage','historical','rarity','scientific','legal'],
    live:false,
  },
  chemistry: {
    sources:[
      {icon:'🧪',name:'PubChem — NIH Compound Database',url:'pubchem.ncbi.nlm.nih.gov',info:'116M+ substances: structure, properties, safety data, biological activity'},
      {icon:'⚗️',name:'NIST Chemistry WebBook',url:'webbook.nist.gov',info:'Thermophysical properties, spectra, reaction data, standard references'},
      {icon:'🔬',name:'Royal Society of Chemistry',url:'rsc.org',info:'Element properties, compound synthesis, safety classifications'},
      {icon:'🌍',name:'ECHA — European Chemicals Agency',url:'echa.europa.eu',info:'REACH registration, hazard classification, restricted substances list'},
          {icon:'📖',name:'Wikipedia — Chemistry & Elements',url:'en.wikipedia.org',info:'Element/compound discovery, Nobel Prize context, industrial uses, safety classification, reaction mechanisms, allotrope descriptions'},
      {icon:'📖',name:'Wikipedia — Chemistry & Elements',url:'en.wikipedia.org',info:'Element discovery, Nobel Prize context, industrial uses, safety classification, reaction mechanisms, allotrope descriptions'},
    ],
    dims:['scientific','industrial','rarity','monetary','legal','ecological'],
    live:false,
  },
  hotels: {
    sources:[
      {icon:'⭐',name:'Forbes Travel Guide',url:'forbestravelguide.com',info:'5-star inspection criteria, service standards, facility requirements'},
      {icon:'🏨',name:'STR Hotel Data — CoStar',url:'str.com',info:'ADR, RevPAR, occupancy rates by market, competitive set benchmarking'},
      {icon:'🌍',name:'Booking.com / Expedia Market Data',url:'booking.com',info:'Real-time rate intelligence, guest review scores, room type pricing'},
      {icon:'💰',name:'HVS Hotel Valuation',url:'hvs.com',info:'Hotel asset valuations, cap rates, development cost per key by market'},
      {icon:'🏛️',name:'Historic Hotels of the World',url:'historichotels.org',info:'Heritage designations, building age, architectural period, renovation records'},
          {icon:'📖',name:'Wikipedia — Hospitality & Hotels',url:'en.wikipedia.org',info:'Hotel chain history, founding year, flagship properties, brand standards, notable guests, architectural heritage'},
      {icon:'📖',name:'Wikipedia — Hospitality Industry',url:'en.wikipedia.org',info:'Hotel chain history, founding year, flagship properties, brand standards, notable guests, architectural heritage'},
    ],
    dims:['monetary','heritage','rarity','aesthetic','tourism','condition'],
    live:false,
  },
  music: {
    sources:[
      {icon:'🎵',name:'AllMusic Database',url:'allmusic.com',info:'Artist discographies, album ratings, genre classifications, band lineups, release history'},
      {icon:'🎸',name:'Vintage Guitar Price Guide',url:'vintageguitar.com',info:'Instrument valuations by brand/year/condition, auction results, collector demand'},
      {icon:'📀',name:'Discogs Marketplace',url:'discogs.com',info:'Vinyl/CD/cassette catalog, pressing variants, collector prices, label history'},
      {icon:'🏆',name:'Grammy Awards Archive',url:'grammy.com',info:'Award history by artist/album, nomination records, cultural impact data'},
      {icon:'💰',name:'Reverb.com Instrument Pricing',url:'reverb.com',info:'Real-time used instrument prices, vintage gear valuations, market trends'},
      {icon:'📖',name:'Wikipedia — Music History',url:'en.wikipedia.org',info:'Artist biography, genre origins, music theory, instrument history, cultural movements'},
    ],
    dims:['monetary','heritage','rarity','aesthetic','historical','condition'],
    live:false,
  },
  aviation: {
    sources:[
      {icon:'✈️',name:"Jane's All the World's Aircraft",url:'janes.com/aircraft',info:'Aircraft specifications, performance data, operator lists, production numbers'},
      {icon:'📊',name:'ch-aviation Fleet Database',url:'ch-aviation.com',info:'Global airline fleets, aircraft age, lease data, route networks'},
      {icon:'💰',name:'AVAC Aircraft Valuations',url:'avac.us',info:'Commercial aircraft appraisals, residual value forecasts, lease rates'},
      {icon:'🛫',name:'Planespotters.net',url:'planespotters.net',info:'Individual aircraft histories, registration data, photo archives'},
      {icon:'📖',name:'Wikipedia — Aviation History',url:'en.wikipedia.org',info:'Aircraft design history, aviation milestones, manufacturer backgrounds, accident records'},
    ],
    dims:['monetary','heritage','rarity','scientific','historical','condition'],
    live:false,
  },
  biology: {
    sources:[
      {icon:'🧬',name:'NCBI — GenBank',url:'ncbi.nlm.nih.gov',info:'DNA sequences, protein structures, genomic data, taxonomic classifications'},
      {icon:'🔬',name:'PubMed Life Sciences',url:'pubmed.ncbi.nlm.nih.gov',info:'Peer-reviewed biology research, cell biology, genetics, molecular biology'},
      {icon:'🌱',name:'Encyclopedia of Life (EOL)',url:'eol.org',info:'1.9M+ species profiles, morphology, ecology, distribution, behavior'},
      {icon:'📊',name:'GBIF — Global Biodiversity',url:'gbif.org',info:'Species occurrence records, geographic range, population data'},
      {icon:'📖',name:'Wikipedia — Biology & Life Sciences',url:'en.wikipedia.org',info:'Species taxonomy, biological processes, evolutionary history, cellular mechanisms'},
    ],
    dims:['scientific','rarity','ecological','heritage','historical','legal'],
    live:false,
  },
  software: {
    sources:[
      {icon:'💻',name:'G2 Software Reviews',url:'g2.com',info:'Enterprise software ratings, pricing tiers, feature comparisons, user counts'},
      {icon:'📊',name:'Statista Software Market',url:'statista.com/software',info:'Market size by segment, revenue data, growth forecasts, vendor shares'},
      {icon:'🔍',name:'Product Hunt',url:'producthunt.com',info:'App launches, upvotes, maker profiles, category rankings, launch dates'},
      {icon:'💰',name:'AppFollow / Sensor Tower',url:'appfollow.io',info:'App store rankings, revenue estimates, download counts, review analytics'},
      {icon:'📖',name:'Wikipedia — Software History',url:'en.wikipedia.org',info:'Software development history, programming language origins, company backgrounds, OS evolution'},
    ],
    dims:['monetary','scientific','rarity','heritage','industrial','aesthetic'],
    live:false,
  },
  oceanography: {
    sources:[
      {icon:'🌊',name:'NOAA Ocean Data',url:'noaa.gov/ocean',info:'Sea temperature, salinity, current data, tidal measurements, bathymetric charts'},
      {icon:'🐋',name:'Ocean Biodiversity Info System',url:'obis.org',info:'Marine species occurrence, depth records, global distribution maps'},
      {icon:'📡',name:'Copernicus Marine Service',url:'marine.copernicus.eu',info:'Satellite ocean observations, sea level rise data, Arctic/Antarctic monitoring'},
      {icon:'🗺️',name:'GEBCO Ocean Mapping',url:'gebco.net',info:'Global seafloor topography, underwater mountain ranges, trench depths'},
      {icon:'📖',name:'Wikipedia — Oceanography',url:'en.wikipedia.org',info:'Ocean zones, current systems, tidal mechanics, deep sea phenomena, exploration history'},
    ],
    dims:['scientific','ecological','rarity','heritage','historical','aesthetic'],
    live:false,
  },
  sports: {
    sources:[
      {icon:'🏆',name:'Sports Reference Databases',url:'sports-reference.com',info:'Complete stats for MLB/NBA/NFL/soccer, player records, team histories'},
      {icon:'💰',name:'StockX Sports Collectibles',url:'stockx.com',info:'Trading card prices, jersey valuations, sneaker markets, memorabilia data'},
      {icon:'🃏',name:'PSA Card Grading',url:'psacard.com',info:'Sports card authentication, population reports, graded card auction values'},
      {icon:'🎽',name:'Transfermarkt',url:'transfermarkt.com',info:'Football player market values, transfer fees, contract data, club valuations'},
      {icon:'📖',name:'Wikipedia — Sports History',url:'en.wikipedia.org',info:'Sport origins, record holders, championship histories, athlete biographies, rule evolution'},
    ],
    dims:['monetary','heritage','rarity','historical','condition','provenance'],
    live:false,
  },
  agriculture: {
    sources:[
      {icon:'🌾',name:'FAO Agricultural Data',url:'fao.org/faostat',info:'Crop production by country, yield per hectare, trade volumes, price indices'},
      {icon:'📊',name:'USDA World Agricultural Supply',url:'usda.gov/wasde',info:'Monthly commodity forecasts: wheat, corn, soy, cotton, rice prices'},
      {icon:'🌱',name:'CGIAR Research Centers',url:'cgiar.org',info:'Seed variety databases, drought resistance ratings, yield improvement data'},
      {icon:'💰',name:'CME Agricultural Futures',url:'cmegroup.com/agriculture',info:'Live commodity futures: corn, wheat, soybeans, cattle, hogs'},
      {icon:'📖',name:'Wikipedia — Agriculture & Crops',url:'en.wikipedia.org',info:'Crop domestication history, farming techniques, irrigation systems, agrarian societies'},
    ],
    dims:['monetary','ecological','scientific','heritage','industrial','historical'],
    live:true,
  },
  cinema: {
    sources:[
      {icon:'🎬',name:'IMDb Pro',url:'imdb.com',info:'Box office data, budget figures, cast/crew, production details, awards history'},
      {icon:'🍅',name:'Rotten Tomatoes / Metacritic',url:'rottentomatoes.com',info:'Critical scores, audience ratings, review aggregation, award nominations'},
      {icon:'💰',name:'The Numbers Box Office',url:'the-numbers.com',info:'Worldwide grosses, opening weekends, home video revenues, franchise performance'},
      {icon:'🏆',name:'Academy Awards Archive',url:'oscars.org',info:'Oscar history, nomination records, craft categories, historical winners'},
      {icon:'📖',name:'Wikipedia — Film & Cinema',url:'en.wikipedia.org',info:'Film history, director biographies, movement classifications, production context, cultural impact'},
    ],
    dims:['monetary','aesthetic','heritage','rarity','historical','provenance'],
    live:false,
  },
  fitness: {
    sources:[
      {icon:'🏋️',name:'American College of Sports Medicine',url:'acsm.org',info:'Exercise science standards, equipment safety ratings, training protocols'},
      {icon:'💰',name:'Fitness Equipment Reviews',url:'garage-gym-reviews.com',info:'Equipment pricing, durability ratings, brand comparisons, resale values'},
      {icon:'📊',name:'IHRSA Health Club Data',url:'ihrsa.org',info:'Gym industry statistics, equipment market size, membership trend data'},
      {icon:'📖',name:'Wikipedia — Fitness & Exercise',url:'en.wikipedia.org',info:'Exercise history, muscle anatomy, training methodology, Olympic sport origins'},
    ],
    dims:['monetary','scientific','heritage','condition','aesthetic','industrial'],
    live:false,
  },
  maritime: {
    sources:[
      {icon:'🚢',name:"Lloyd's Register of Shipping",url:'lr.org',info:'Ship classification, tonnage records, safety certificates, vessel histories'},
      {icon:'📊',name:'Clarksons Research',url:'clarksons.com',info:'Ship values, charter rates, newbuilding prices, fleet statistics by type'},
      {icon:'🗺️',name:'MarineTraffic AIS Data',url:'marinetraffic.com',info:'Vessel tracking, port calls, speed data, route histories'},
      {icon:'💰',name:'VesselsValue',url:'vesselsvalue.com',info:'Real-time ship valuations, demolition prices, sale & purchase records'},
      {icon:'📖',name:'Wikipedia — Maritime & Naval History',url:'en.wikipedia.org',info:'Ship design evolution, naval battle history, maritime trade routes, famous vessels'},
    ],
    dims:['monetary','heritage','historical','rarity','industrial','condition'],
    live:false,
  },
  mythology: {
    sources:[
      {icon:'🗿',name:'Theoi Greek Mythology',url:'theoi.com',info:'Complete Greek divine genealogies, myth variants, ancient source citations'},
      {icon:'📜',name:'Sacred Texts Archive',url:'sacred-texts.com',info:'Primary mythological texts: Norse Eddas, Egyptian Book of the Dead, Vedas'},
      {icon:'🏛️',name:'Oxford Classical Dictionary',url:'oxfordre.com/classics',info:'Scholarly articles on mythology, religion, iconography, cult practices'},
      {icon:'🌍',name:'Encyclopedia Mythica',url:'pantheon.org',info:'Cross-cultural mythology database: 7,000+ articles on myths and legends'},
      {icon:'📖',name:'Wikipedia — World Mythology',url:'en.wikipedia.org',info:'Pantheon descriptions, creation myths, hero archetypes, comparative mythology, cultural context'},
    ],
    dims:['heritage','historical','rarity','aesthetic','scientific','legal'],
    live:false,
  },
  climate: {
    sources:[
      {icon:'🌡️',name:'NASA GISS Surface Temperature',url:'data.giss.nasa.gov',info:'Global temperature records since 1880, anomaly maps, station data'},
      {icon:'📊',name:'IPCC Climate Reports',url:'ipcc.ch',info:'Scientific consensus reports, emissions scenarios, regional impact projections'},
      {icon:'🌍',name:'Copernicus Climate Change Service',url:'climate.copernicus.eu',info:'European climate data, monthly bulletins, extreme event records'},
      {icon:'⚡',name:'Our World in Data — Climate',url:'ourworldindata.org/climate',info:'CO2 emissions by country, energy mix data, policy effectiveness metrics'},
      {icon:'📖',name:'Wikipedia — Climate & Meteorology',url:'en.wikipedia.org',info:'Climate system mechanics, historical climate events, weather phenomena, biome descriptions'},
    ],
    dims:['scientific','ecological','historical','heritage','legal','industrial'],
    live:false,
  },
  crafts: {
    sources:[
      {icon:'🧶',name:'Etsy Market Intelligence',url:'etsy.com',info:'Handcraft pricing by category, seller competition, trending items, buyer demographics'},
      {icon:'🏺',name:'World Crafts Council',url:'worldcraftscouncil.org',info:'Traditional craft documentation, master artisan recognition, endangered crafts'},
      {icon:'💰',name:'1stDibs Decorative Arts',url:'1stdibs.com',info:'High-end craft and decorative art pricing, provenance requirements, dealer data'},
      {icon:'📖',name:'Wikipedia — Crafts & Textile Arts',url:'en.wikipedia.org',info:'Craft tradition history, technique descriptions, regional styles, material origins'},
    ],
    dims:['monetary','heritage','rarity','aesthetic','historical','condition'],
    live:false,
  },
  education: {
    sources:[
      {icon:'🎓',name:'QS World University Rankings',url:'topuniversities.com',info:'University rankings, subject scores, employer reputation, research citations'},
      {icon:'📊',name:'OECD Education at a Glance',url:'oecd.org/education',info:'Global education statistics, graduation rates, return on education investment'},
      {icon:'💰',name:'Coursera / edX Market Data',url:'coursera.org',info:'Online course pricing, completion rates, job placement outcomes by certification'},
      {icon:'📖',name:'Wikipedia — Education Systems',url:'en.wikipedia.org',info:'Educational institution histories, degree system origins, academic discipline development'},
    ],
    dims:['monetary','scientific','heritage','historical','rarity','aesthetic'],
    live:false,
  },
  physics: {
    sources:[
      {icon:'⚛️',name:'CERN Document Server',url:'cds.cern.ch',info:'Particle physics papers, detector data, experimental results, Nobel Prize research'},
      {icon:'🔬',name:'APS Physics Journals',url:'journals.aps.org',info:'Physical Review publications, breakthrough discoveries, theoretical frameworks'},
      {icon:'📊',name:'NIST Physical Constants',url:'nist.gov/physics',info:'Fundamental constants, measurement standards, SI unit definitions'},
      {icon:'📖',name:'Wikipedia — Physics & Quantum Science',url:'en.wikipedia.org',info:'Physics history, theory explanations, famous experiments, Nobel laureate biographies'},
    ],
    dims:['scientific','historical','heritage','rarity','aesthetic','industrial'],
    live:false,
  },
  dental: {
    sources:[
      {icon:'🦷',name:'ADA — American Dental Association',url:'ada.org',info:'Dental procedure codes, material standards, treatment guidelines, device classifications'},
      {icon:'💰',name:'Healthcare Bluebook — Dental',url:'healthcarebluebook.com',info:'Fair price estimates for dental procedures by region, insurance benchmark data'},
      {icon:'🔬',name:'Cochrane Oral Health',url:'cochrane.org/oral-health',info:'Evidence-based dental treatment reviews, clinical trial summaries'},
      {icon:'📖',name:'Wikipedia — Dentistry & Oral Health',url:'en.wikipedia.org',info:'Dental history, tooth anatomy, procedure descriptions, material science, orthodontics'},
    ],
    dims:['monetary','scientific','heritage','condition','legal','aesthetic'],
    live:false,
  },
  cybersecurity: {
    sources:[
      {icon:'🔐',name:'CVE — MITRE Vulnerability Database',url:'cve.mitre.org',info:'Common Vulnerabilities and Exposures catalog, severity scores, patch status'},
      {icon:'🛡️',name:'NIST Cybersecurity Framework',url:'nist.gov/cyberframework',info:'Security control standards, risk assessment methodology, compliance frameworks'},
      {icon:'📊',name:'Gartner Security Market Data',url:'gartner.com/security',info:'Cybersecurity product rankings, market size, vendor evaluations, Magic Quadrant'},
      {icon:'📖',name:'Wikipedia — Cybersecurity',url:'en.wikipedia.org',info:'Hacking history, cryptography origins, famous breaches, security protocol development'},
    ],
    dims:['scientific','monetary','legal','rarity','industrial','historical'],
    live:false,
  },
  baby: {
    sources:[
      {icon:'👶',name:'BabyCenter Product Safety',url:'babycenter.com',info:'Product recalls, safety ratings, developmental milestone context, expert reviews'},
      {icon:'💰',name:'Consumer Reports — Baby',url:'consumerreports.org',info:'Car seat crash test scores, stroller ratings, crib safety standards, price comparisons'},
      {icon:'📊',name:'Juvenile Products Manufacturers Assoc.',url:'jpma.org',info:'Safety certification (JPMA), voluntary standards, product category data'},
      {icon:'📖',name:'Wikipedia — Child Development',url:'en.wikipedia.org',info:'Developmental psychology, pediatric health standards, product safety history'},
    ],
    dims:['monetary','scientific','legal','condition','heritage','aesthetic'],
    live:false,
  },
  plastics: {
    sources:[
      {icon:'🧪',name:'Plastics Industry Association',url:'plasticsindustry.org',info:'Resin pricing, material properties, recycling codes, production statistics'},
      {icon:'💰',name:'ICIS Polymer Pricing',url:'icis.com/polymers',info:'Live polymer prices: HDPE, PET, PP, PVC, ABS — global market data'},
      {icon:'🌍',name:'Ellen MacArthur Foundation — Plastics',url:'ellenmacarthurfoundation.org',info:'Plastic lifecycle data, recycling rates, ocean pollution statistics'},
      {icon:'📖',name:'Wikipedia — Polymers & Plastics',url:'en.wikipedia.org',info:'Plastic discovery history, chemical composition, environmental impact, industrial applications'},
    ],
    dims:['monetary','industrial','ecological','scientific','legal','rarity'],
    live:true,
  },
  paranormal: {
    sources:[
      {icon:'🛸',name:'MUFON UFO Database',url:'mufon.com',info:'UFO sighting reports, witness testimonies, geographic clustering, investigation findings'},
      {icon:'🔬',name:'Scientific Coalition for UAP Studies',url:'explorescu.org',info:'Peer-reviewed UAP research, sensor data analysis, government declassified reports'},
      {icon:'📜',name:'Fortean Times Archive',url:'forteantimes.com',info:'Historical paranormal documentation, cryptid reports, anomalous phenomena catalog'},
      {icon:'📖',name:'Wikipedia — Paranormal & Unexplained',url:'en.wikipedia.org',info:'Paranormal phenomena history, psychological explanations, famous cases, cultural impact'},
    ],
    dims:['scientific','heritage','historical','rarity','aesthetic','legal'],
    live:false,
  },

};

/* Fallback for categories not in ARCHIVE_DB */
const DEFAULT_ARCHIVE = {
  sources:[
    {icon:'📖',name:'Wikipedia — General Knowledge',url:'en.wikipedia.org',info:'Encyclopedic reference: taxonomy, history, cultural context, technical specs, geographic data, citation network'},
    {icon:'📚',name:'Google Scholar',url:'scholar.google.com',info:'Academic publications, citation counts, open access papers'},
    {icon:'🔍',name:'Wolfram Alpha',url:'wolframalpha.com',info:'Computational knowledge, factual data, unit conversions, statistics'},
    {icon:'🌐',name:'Britannica Encyclopedia',url:'britannica.com',info:'Expert-curated encyclopedic articles, peer-reviewed content, historical depth'},
  ],
  dims:['monetary','heritage','rarity','scientific','aesthetic','legal'],
  live:false,
};

/* ===== CATEGORIES LIST ===== */
const CATS=[
  /* ── TIER 1: HIGHEST GLOBAL DEMAND ── */
  {key:'food',e:'🍕',n:'Food & Cuisine',d:'Dishes, restaurants, ingredients + prices'},
  {key:'cars',e:'🚗',n:'Vehicles',d:'Cars, specs, market value'},
  {key:'electronics',e:'⚡',n:'Electronics',d:'Devices, components, specs + prices'},
  {key:'fashion',e:'👗',n:'Fashion',d:'Brands, trends, retail prices'},
  {key:'medicine',e:'💊',n:'Medicine',d:'Drugs, devices, dosage info'},
  {key:'realestate',e:'🏠',n:'Real Estate',d:'Land & buildings by region'},
  {key:'sports',e:'🏆',n:'Sports & Collectibles',d:'Cards, memorabilia, player values'},
  {key:'software',e:'💻',n:'Software & Apps',d:'Apps, platforms, SaaS pricing'},
  {key:'baby',e:'👶',n:'Baby & Kids Products',d:'Safety ratings, pricing, development'},
  {key:'fitness',e:'🏋️',n:'Fitness Equipment',d:'Gym gear, ratings, resale values'},
  /* ── TIER 2: HIGH DEMAND ── */
  {key:'animals',e:'🐾',n:'Animals',d:'Wildlife, pets, livestock + prices'},
  {key:'plants',e:'🌿',n:'Plants & Trees',d:'Botany, rarity, heritage + value'},
  {key:'music',e:'🎵',n:'Music & Instruments',d:'Gear, vinyl, artist data + prices'},
  {key:'cinema',e:'🎬',n:'Film & Cinema',d:'Movies, box office, awards, history'},
  {key:'gaming',e:'🎮',n:'Gaming',d:'Games, consoles, collectibles + prices'},
  {key:'art',e:'🎨',n:'Art & Paintings',d:'Artists, movements, auction estimates'},
  {key:'gems',e:'💎',n:'Gems & Jewelry',d:'Stones, purity, market prices'},
  {key:'currency',e:'💵',n:'Currency',d:'Banknotes, coins, crypto + rates'},
  {key:'metals',e:'🥇',n:'Metals',d:'Gold, copper, silver — live prices'},
  {key:'energy',e:'⛽',n:'Oil & Energy',d:'Petroleum, gas — live prices'},
  /* ── TIER 3: SPECIALIST DEMAND ── */
  {key:'agriculture',e:'🌾',n:'Agriculture & Crops',d:'Commodities, seeds, farm pricing'},
  {key:'construction',e:'🏗️',n:'Construction',d:'Building materials by country'},
  {key:'architecture',e:'🏛️',n:'Architecture',d:'Buildings, styles, cost per m²'},
  {key:'books',e:'📚',n:'Books & Manuscripts',d:'Rare editions + collector value'},
  {key:'artifacts',e:'🏺',n:'Artifacts',d:'Historical objects + multi-layer value'},
  {key:'palaces',e:'🏰',n:'Palaces & Castles',d:'Historic estates + UNESCO value'},
  {key:'hotels',e:'🏨',n:'Hotels',d:'Hospitality, stars + price ranges'},
  {key:'aviation',e:'✈️',n:'Aviation',d:'Aircraft specs, fleet, valuations'},
  {key:'maritime',e:'🚢',n:'Maritime & Ships',d:'Vessel history, charter, valuations'},
  {key:'plastics',e:'🧪',n:'Plastics & Polymers',d:'Resin types, prices, recycling'},
  /* ── TIER 4: KNOWLEDGE & SCIENCE ── */
  {key:'biology',e:'🧬',n:'Biology & Life Sciences',d:'Genomics, species, ecology'},
  {key:'chemistry',e:'⚗️',n:'Chemistry',d:'Compounds, elements, safety data'},
  {key:'physics',e:'⚛️',n:'Physics & Quantum',d:'Particles, constants, experiments'},
  {key:'space',e:'🌌',n:'Space & Cosmos',d:'Galaxies, stars — precise data'},
  {key:'oceanography',e:'🌊',n:'Oceanography',d:'Ocean data, marine phenomena'},
  {key:'climate',e:'🌡️',n:'Climate & Weather',d:'Temperature data, IPCC reports'},
  {key:'cybersecurity',e:'🔐',n:'Cybersecurity',d:'Vulnerabilities, tools, frameworks'},
  {key:'education',e:'🎓',n:'Education & Certificates',d:'Universities, rankings, ROI'},
  {key:'dental',e:'🦷',n:'Dental & Medical Devices',d:'Procedures, devices, pricing'},
  {key:'psychology',e:'🧠',n:'Psychology',d:'Concepts, disorders, theories'},
  /* ── TIER 5: CULTURE & HERITAGE ── */
  {key:'religion',e:'☪️',n:'Religion',d:'Symbols, texts, traditions'},
  {key:'sociology',e:'👥',n:'Sociology',d:'Social phenomena, demographics'},
  {key:'mythology',e:'🗿',n:'Mythology & Legends',d:'Pantheons, myths, symbolism'},
  {key:'flags',e:'🚩',n:'Flags & Nations',d:'Countries, symbolism, context'},
  {key:'crafts',e:'🧶',n:'Crafts & Textiles',d:'Handmade arts, traditional crafts'},
  {key:'marine',e:'🐠',n:'Marine Life',d:'Fish, coral, sea creatures + prices'},
  {key:'weapons',e:'🪖',n:'Military & Weapons',d:'Historical arms, specifications'},
  {key:'ads',e:'📢',n:'Advertising',d:'Ad boards, CPM/CPC market data'},
  {key:'paranormal',e:'🛸',n:'UFO & Paranormal',d:'UAP reports, unexplained phenomena'},
];

const DMETA={
  monetary:     {e:'💰',l:'Market Value',      c:'#f59e0b'},
  heritage:     {e:'🏛️',l:'Heritage Value',   c:'#a78bfa'},
  rarity:       {e:'🔮',l:'Rarity',             c:'#00d4ff'},
  scientific:   {e:'🔬',l:'Scientific Value',   c:'#22c55e'},
  aesthetic:    {e:'✨',l:'Aesthetic Value',    c:'#ec4899'},
  legal:        {e:'⚖️',l:'Legal Protection',  c:'#f87171'},
  medicinal:    {e:'💊',l:'Medicinal Value',    c:'#34d399'},
  ecological:   {e:'🌍',l:'Ecological Impact',  c:'#4ade80'},
  numismatic:   {e:'🪙',l:'Numismatic Value',   c:'#fbbf24'},
  historical:   {e:'📜',l:'Historical Depth',   c:'#c084fc'},
  condition:    {e:'📊',l:'Condition Score',    c:'#60a5fa'},
  architectural:{e:'🏗️',l:'Arch. Value',       c:'#fb923c'},
  tourism:      {e:'🗺️',l:'Tourism Potential', c:'#2dd4bf'},
  ethical:      {e:'🕊️',l:'Ethical Standing',  c:'#86efac'},
  provenance:   {e:'📋',l:'Provenance',         c:'#c4b5fd'},
  industrial:   {e:'⚙️',l:'Industrial Demand', c:'#94a3b8'},
  investment:   {e:'📈',l:'Investment Grade',   c:'#fde68a'},
  purity:       {e:'✅',l:'Purity / Quality',   c:'#6ee7b7'},
};


function getArchive(cat){ return ARCHIVE_DB[cat]||DEFAULT_ARCHIVE; }

function getDims(cat){const a=getArchive(cat);return a.dims;}

const TIERS=[
  {label:'&#128293; HIGHEST DEMAND',tcls:'t1',keys:['food','cars','electronics','fashion','medicine','realestate','sports','software','baby','fitness']},
  {label:'&#128200; HIGH DEMAND',tcls:'t2',keys:['animals','plants','music','cinema','gaming','art','gems','currency','metals','energy']},
  {label:'&#128295; SPECIALIST',tcls:'t3',keys:['agriculture','construction','architecture','books','artifacts','palaces','hotels','aviation','maritime','plastics']},
  {label:'&#128300; SCIENCE & TECH',tcls:'t4',keys:['biology','chemistry','physics','space','oceanography','climate','cybersecurity','education','dental','psychology']},
  {label:'&#127963; CULTURE & HERITAGE',tcls:'t5',keys:['religion','sociology','mythology','flags','crafts','marine','weapons','ads','paranormal']},
];
